apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
    - image: cloud.canister.io:5000/wolnik/nodeskaff
      context: backend
      sync:
        "*.js": .
deploy:
  kubectl:
    manifests:
      - "backend/k8s/**"
      - "kubernetes-manifests/**"
